[package]
name = "cosmic-applet-cpu-temp"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["applet", "tokio", "wayland"]

